repo: "letter-looper-triangle"
canvasCourse: "467503"
canvasAssignment: "4202494"

naming: true
commits: 1

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - "script"

js:
  - path: "js/main.js"
    valid: true
    bestPractices: true
    search:
      - "var"
      - "prompt"
      - "for"
      - "(9|10|11)"
      - "document.write"
